test: &default


  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: "paloma-facilitator_api1.maximilianodeyork.com"
  password: "1385743679"
  signature: "Api-EGlR9MBGCCR71bss7X.AKzIqAgFY5IUqzAGvzJX.vULuQfpzMYAN"
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: info@maximilianodoyork.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
